In [2]:
#import libraries
# !pip3 install face_recognition

# !pip3 install face_recognition torch torchvision matplotlib
# !pip3 install opencv-python
!pip3 install torchsummary
import torch
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
# import face_recognition

In [3]:
#import libraries
import torch
from torch.autograd import Variable
import time
import os
import sys
import os
from torch import nn
from torchvision import models

In [4]:
#Model with feature visualization
from torch import nn
from torchvision import models
class Model(nn.Module):
    def __init__(self, num_classes,latent_dim= 2048, lstm_layers=1 , hidden_dim = 2048, bidirectional = False):
        super(Model, self).__init__()
        model = models.resnext50_32x4d(pretrained = True)
        self.model = nn.Sequential(*list(model.children())[:-2])
        self.lstm = nn.LSTM(latent_dim,hidden_dim, lstm_layers,  bidirectional)
        self.relu = nn.LeakyReLU()
        self.dp = nn.Dropout(0.4)
        self.linear1 = nn.Linear(2048,num_classes)
        self.avgpool = nn.AdaptiveAvgPool2d(1)
    def forward(self, x):
        batch_size,seq_length, c,  h, w = x.shape
        x = x.view(batch_size * seq_length, c, h, w)
        fmap = self.model(x)
        x = self.avgpool(fmap)
        x = x.view(batch_size,seq_length,2048)
        x_lstm,_ = self.lstm(x,None)
        return fmap,self.dp(self.linear1(x_lstm[:,-1,:]))

In [5]:
im_size = 112
mean=[0.485, 0.456, 0.406]
std=[0.229, 0.224, 0.225]
sm = nn.Softmax()
inv_normalize =  transforms.Normalize(mean=-1*np.divide(mean,std),std=np.divide([1,1,1],std))
def im_convert(tensor):
    """ Display a tensor as an image. """
    image = tensor.to("cpu").clone().detach()
    image = image.squeeze()
    image = inv_normalize(image)
    image = image.numpy()
    image = image.transpose(1,2,0)
    image = image.clip(0, 1)
    cv2.imwrite('./2.png',image*255)
    return image

def predict(model,img,path = './'):
  fmap,logits = model(img.to('cpu'))
  params = list(model.parameters())
  weight_softmax = model.linear1.weight.detach().cpu().numpy()
  print('Before Softmax')
  print(logits)
  logits = sm(logits)
  print('After Softmax')
  print(logits)
  # _,prediction = torch.max(logits,1)
  predictionVal = logits[0][1]
  print(predictionVal)
  # confidence = logits[:,int(prediction.item())].item()*100
  # print('confidence of prediction:',logits[:,int(prediction.item())].item()*100)
  confidence = predictionVal*100
  print('confidence of prediction: ',predictionVal*100)
  idx = np.argmax(logits.detach().cpu().numpy())
  bz, nc, h, w = fmap.shape
  out = np.dot(fmap[-1].detach().cpu().numpy().reshape((nc, h*w)).T,weight_softmax[idx,:].T)
  predict = out.reshape(h,w)
  predict = predict - np.min(predict)
  predict_img = predict / np.max(predict)
  predict_img = np.uint8(255*predict_img)
  out = cv2.resize(predict_img, (im_size,im_size))
  heatmap = cv2.applyColorMap(out, cv2.COLORMAP_JET)
  img = im_convert(img[:,-1,:,:,:])
  result = heatmap * 0.5 + img*0.8*255
  cv2.imwrite('/content/1.png',result)
  result1 = heatmap * 0.5/255 + img*0.8
  r,g,b = cv2.split(result1)
  result1 = cv2.merge((r,g,b))
  plt.imshow(result1)
  plt.show()
  # return [int(prediction.item()),confidence]
  return confidence
#img = train_data[100][0].unsqueeze(0)
#predict(model,img)

In [6]:
#!pip3 install face_recognition
import torch
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader
from torch.utils.data.dataset import Dataset
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import face_recognition
class validation_dataset(Dataset):
    def __init__(self,video_names,sequence_length = 60,transform = None):
        self.video_names = video_names
        self.transform = transform
        self.count = sequence_length
    def __len__(self):
        return len(self.video_names)
    def __getitem__(self,idx):
        video_path = self.video_names[idx]
        frames = []
        a = int(100/self.count)
        first_frame = np.random.randint(0,a)
        for i,frame in enumerate(self.frame_extract(video_path)):
            #if(i % a == first_frame):
            faces = face_recognition.face_locations(frame)
            try:
              top,right,bottom,left = faces[0]
              frame = frame[top:bottom,left:right,:]
            except:
              pass
            frames.append(self.transform(frame))
            if(len(frames) == self.count):
              break
        print("no of frames",len(frames))
        frames = torch.stack(frames)
        frames = frames[:self.count]
        return frames.unsqueeze(0)
    def frame_extract(self,path):
      vidObj = cv2.VideoCapture(path)
      success = 1
      while success:
          success, image = vidObj.read()
          if success:
              yield image
def im_plot(tensor):
    image = tensor.cpu().numpy().transpose(1,2,0)
    b,g,r = cv2.split(image)
    image = cv2.merge((r,g,b))
    image = image*[0.22803, 0.22145, 0.216989] +  [0.43216, 0.394666, 0.37645]
    image = image*255.0
    plt.imshow(image.astype(int))
    plt.show()

In [7]:
from torchsummary import summary

#Code for making prediction
im_size = 112
mean=[0.485, 0.456, 0.406]
std=[0.229, 0.224, 0.225]

train_transforms = transforms.Compose([
                                        transforms.ToPILImage(),
                                        transforms.Resize((im_size,im_size)),
                                        transforms.ToTensor(),
                                        transforms.Normalize(mean,std)])

model = Model(2)
path_to_model = 'FF_88_acc_seqLen_20_Confusion_matrix.pth'
model.load_state_dict(torch.load(path_to_model, map_location=torch.device('cpu')))
model.eval()

# for i in range(0,len(path_to_videos)):
#   print(path_to_videos[i])
#   predictConfidence = predict(model,video_dataset[i],'./')
#   # print(predictConfidence[0])
#   # print('---')
#   # print(predictConfidence[1])
#   # if predictConfidence[0] == 1:
#   #   print("REAL")
#   # else:
#   #   print("FAKE")
#   if predictConfidence > 60:
#     print(f"With {predictConfidence} confidence it is a REAL video")
#   else:
#     tempX = 100 - predictConfidence
#     print(f"With {tempX} confidence it is a Deep Faked video")

/home/abhishek/hello/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/abhishek/hello/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNeXt50_32X4D_Weights.IMAGENET1K_V1`. You can also use `weights=ResNeXt50_32X4D_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/tmp/ipykernel_1781/440959172.py:16: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY

Model(
  (model): Sequential(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (4): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (downsample): Sequential(
          (0)

In [ ]:
def fakeOrNot(VideoFileName):
  full_path_to_videos = VideoFileName
  path_to_videos_list = [full_path_to_videos]
  print(path_to_videos_list[0])
  video_dataset = validation_dataset(path_to_videos_list,sequence_length = 60,transform = train_transforms)
  predictConfidence = predict(model,video_dataset[0],'./')
  if predictConfidence > 60:
    return (f"With {predictConfidence} confidence it is a REAL video")
  else:
    tempX = 100 - predictConfidence
    return (f"With {tempX} confidence it is a Deep Faked video")
  # if predictConfidence > 65:
  #   return (f"It is a REAL video.")
  # else:
  #   tempX = 100 - predictConfidence
  #   return (f"It is Deep Faked video.")

In [9]:
!pip3 install gradio

In [10]:
# Path input Working

# def video_identity(videoName):
#   return fakeOrNot(videoName)
import gradio as gr

demo = gr.Interface(fn=fakeOrNot, inputs="text", outputs="text", title="Deep Fake Detection", description="Enter the video name to check it is a deepfake video or not.")
demo.launch(debug=True)

# path - /content/drive/MyDrive/LocalFiveSecRealVideo.mp4

* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


id0_0001.mp4
no of frames 60


/home/abhishek/hello/lib/python3.12/site-packages/torch/nn/modules/module.py:1736: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers). Got range [0.05019606277346611..1.2968627214431763].


Before Softmax
tensor([[-8.3609,  8.5814]], grad_fn=<AddmmBackward0>)
After Softmax
tensor([[4.3857e-08, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)
tensor(1., grad_fn=<SelectBackward0>)
confidence of prediction:  tensor(100., grad_fn=<MulBackward0>)


/tmp/ipykernel_1781/1771917768.py:49: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


Recording 2024-12-02 182025.mp4
no of frames 60
Before Softmax
tensor([[ 1.8727, -1.9099]], grad_fn=<AddmmBackward0>)
After Softmax
tensor([[0.9777, 0.0223]], grad_fn=<SoftmaxBackward0>)
tensor(0.0223, grad_fn=<SelectBackward0>)
confidence of prediction:  tensor(2.2256, grad_fn=<MulBackward0>)
Keyboard interruption in main thread... closing server.
